language: php
services: mysql
php:
  - 5.5
  - 5.4
  - 5.3
before_install:
  - composer self-update
before_script:
  - mysql < database/dump.sql
  - composer install
  - cp config/default.json.dist config/default.json