language: php
services: mysql
php:
  - 5.6
  - 5.5
  - 5.4
before_install:
  - composer self-update
before_script:
  - mysql < db/dump.sql
  - composer install
  - cp config/default.json.dist config/default.json
script:
  - node_modules/karma/bin/karma start